sprint 1 step 1
d1sky/stellar_burgers pull request #2
Opened 2023-02-01 05:10 UTC by d1sky

first review

2023-02-01 06:59 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа.

Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;

### **Но есть несколько замечаний, которые нужно исправить:**

- В компоненте App-header требуется поправить семантику, переделать `nav` в ссылки.

- В директории `components` должен быть компонент App. Компонент `App`, он также должен быть в папке (как и другие компоненты). Как правило, это основной компонент в React, который выступает в качестве контейнера для всех остальных компонентов;

- Удалите пустышку: <https://disk.yandex.com/i/n1oF2iBVkh16Vg>;
  А также `README copy.md` в корне проекта;

- Нужно описать propTypes у всех компонентов, где используются пропсы .
  
  Должна быть описана полная структура ингредиента.
  
  И сразу скажу. Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

  Пример как правильно:

  ```js
  //для массива ингредиентов
  data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
  //для 1 ингредиента
  data: ingredientTypes.isRequired;
  ```

  Проверьте во всём проекте.

- Не нужно указывать key, у не итерируемых элементов. Советую ещё раз ознакомится с этой темой: <https://ru.react.js.org/docs/lists-and-keys.html>;

- Старайтесь более осмысленно называть пропсы (в крайнем случае оставляйте комментарии, что это за пропс, если сомневаетесь в названии).

- Исправьте naming компонентов по файлам.
  Например:

  сейчас у вас так:
  
  ```text
  --app-header
    -- AppHeader.jsx
    -- AppHeader.module.css
  ```

  это не совсем корректно, вы не соблюдаете единый тон найминга файлов))

  Лучше сделать вот так:

  ```text
  --app-header
    -- app-header.jsx
    -- app-header.module.css
  ```

  Только перепроверьте проект на ошибки, после того как переименуйте файлы, а то у гита иногда бывают проблемы с изменением регистра у файлов.

### **Сделает код лучше:**

- Используйте функциональные компоненты, а не классовые.

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь <https://learn.javascript.ru/coding-style>. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (<https://prettier.io/>)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-02-01 06:59 UTC, ArslanDev666 commented on src/components/price/Price.jsx
> +export default Price
**Надо исправить:**

не стоит делить такие мелкие куски кода на отдельные компоненты.

2023-02-01 06:59 UTC, ArslanDev666 commented on src/components/burger-constructor/BurgerConstructor.jsx
> +                key={order.length - 1}
**Надо исправить:**

Тут не нужно указывать key, key нужно указывать только тогда, когда рендерится список.

2023-02-01 06:59 UTC, ArslanDev666 commented on src/components/burger-constructor/BurgerConstructor.jsx
> +                key={0}
**Надо исправить:**

Тут не нужно указывать key, key нужно указывать только тогда, когда рендерится список.

2023-02-01 06:59 UTC, ArslanDev666 commented on src/components/burger-constructor/BurgerConstructor.jsx
> +                order={order[0]}
**Надо исправить:**

Здесь и далее.

Лучше сразу разделить булку и ингредиенты.

```js
const bun = data.find(ingredient => inrgedient.type === 'bun');
const ingredients = data.filter(ingredient => inrgedient.type !== 'bun');
```

и потом (Когда изучите), оберните это в useMemo

2023-02-01 06:59 UTC, ArslanDev666 commented on src/components/burger-constructor/BurgerConstructor.jsx
> +const BurgerConstructor = ({ order }) => {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-02-01 06:59 UTC, ArslanDev666 commented on src/components/burger-ingredients/BurgerIngredients.jsx
> +const BurgerIngredients = ({ data }) => {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-02-01 06:59 UTC, ArslanDev666 commented on src/components/burger-ingredients/BurgerIngredients.jsx
> +                <IngredientBlock name={'Начинки'} data={data.filter(it => it.type === 'main')} />
**Можно лучше**

Лучше в компоненте делать filter по массиву, а потом отображать полученный массив.

Например:

```js
const buns = useMemo(data.filter((item) => item.type === 'bun'), [data]);
const mains = useMemo(data.filter((item) => item.type === 'main'), [data]);
const sauces = useMemo(data.filter((item) => item.type === 'sauce'), [data]);

return (
   ....................
   {buns.map(....................)}
   ..................
)
```

А не располагать фильтрацию в самом jsx

2023-02-01 06:59 UTC, ArslanDev666 commented on src/components/card/Card.jsx
> +const Card = ({ card }) => {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-02-01 06:59 UTC, ArslanDev666 commented on src/components/ingredient/Ingredient.jsx
> +    return <div className={IngredientStyle.block} key={key}>
**Надо исправить:**

Тут не нужно передавать key.

2023-02-01 06:59 UTC, ArslanDev666 commented on src/components/ingredient/Ingredient.jsx
> +    let style = IngredientStyle.ingredient + ' ' + (top && IngredientStyle.ingredient_top) + ' ' + (bottom && IngredientStyle.ingredient_bottom);
**Можно лучше**

**здесь и далее в других местах** если переменная не перезаписывается её нужно объявлять как `const`, это помогает понять другим разработчикам, как мы будем использовать переменную, будем ли мы в коде перезаписывать её значение.
Так же стоит помнить, что добавление элемента в массив или изменение свойства объект не являются перезаписью самой переменной, а только изменяют его внутренне состояние и такие переменные так же объявляются как const

2023-02-01 06:59 UTC, ArslanDev666 commented on src/components/ingredient/Ingredient.jsx
> +                    {order.name}
**Надо исправить:**

По макету у булок должна быть приписка `(верх)` и `(низ)`.

2023-02-01 06:59 UTC, ArslanDev666 commented on src/components/ingredient/Ingredient.jsx
> +const Ingredient = ({ order, top, bottom, key }) => {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

И переименуйте `order` в `ingredient`, а то не очень понятно, что это всё таки за пропс.

2023-02-01 06:59 UTC, ArslanDev666 commented on src/components/ingredient-block/IngredientBlock.jsx
> +const IngredientBlock = ({ name, data }) => {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-02-01 19:37 UTC, d1sky commented on src/components/price/Price.jsx
> +export default Price
Код используется в 3х местах, как минимум

2023-02-01 19:51 UTC, d1sky commented on src/components/burger-ingredients/BurgerIngredients.jsx
> +                <IngredientBlock name={'Начинки'} data={data.filter(it => it.type === 'main')} />
const ingredientsCategoryList = [
    {
        name: 'Булки',
        type: 'bun'
    },
    {
        name: 'Соусы',
        type: 'sauce'
    },
    {
        name: 'Начинки',
        type: 'main'
    }
]

  {ingredientsCategoryList.map(category =>
                    <IngredientBlock
                        name={category.name}
                        ingredientList={ingredientsList.filter(imgredient =>
                            imgredient.type === category.type)} />
                )}

2023-02-02 05:10 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                        value={ingredient.name}
**Можно лучше:**

Лучше использовать английский вариант, в качестве значений)

2023-02-02 05:10 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +                                text={product.name}
**Надо исправить:**

Вы должны передавать key в верхний див, а не сюда) 

```js
  <div className={BurgerConstructorStyle.block} key={index}> // ...
```

2023-02-02 05:10 UTC, ArslanMustafin commented on src/components/price/Price.jsx
> +export default Price
Угу, увидел)

2023-02-02 05:10 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Вы молодец! Отличная работа. Можете приступать к финальному этапу задания.**

### **Но перед этим, есть несколько замечаний, которые нужно исправить:**

- В компоненте App-header требуется поправить семантику, не нужно оборачивать каждую ссылку в nav. Советую ещё раз прочитать про nav - <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav>.

- Ещё раз проверьте регистры букв у файлов, они у вас немного в разнобой идут)) <https://disk.yandex.com/i/bN6CUqlcrTO-Yw>;

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили. Проверьте во всём проекте.

2023-02-11 09:30 UTC, merged